services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    volumes:
      - .:/app:cached
      - ${HOME}/.config/gcloud:/root/.config/gcloud:cached
    working_dir: /app
    command: sleep infinity    # VS Code will override with its shell server
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - OPENAI_API_KEY=/root/.z_Do_Not_Sync_or_use/openaikey.secret
    secrets:
      - openaikey.secret
  prod:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.prod
    ports:
      - "8080:8080"